export enum SocietyCategory {
  ACADEMIC = 'ACADEMIC',
  CULTURAL = 'CULTURAL',
  TECHNICAL = 'TECHNICAL',
  SPORTS = 'SPORTS',
  VOLUNTEER = 'VOLUNTEER',
}

export enum MemberDesignation {
  PRESIDENT = 'PRESIDENT',
  VICE_PRESIDENT = 'VICE_PRESIDENT',
  GENERAL_SECRETARY = 'GENERAL_SECRETARY',
  SPORTS_SECRETARY = 'SPORTS_SECRETARY',
  ORGANIZING_SECRETARY = 'ORGANIZING_SECRETARY',
  PUBLICATION_SECRETARY = 'PUBLICATION_SECRETARY',
  ASSISTANT_GENERAL_SECRETARY = 'ASSISTANT_GENERAL_SECRETARY',
  EXECUTIVE_MEMBER = 'EXECUTIVE_MEMBER',
}
