export enum TransactionType {
  INCOME = 'INCOME',
  EXPENSE = 'EXPENSE',
}

export enum TransactionCategory {
  SOCIETY_FUND = 'SOCIETY_FUND',
  EVENT_SPONSORSHIP = 'EVENT_SPONSORSHIP',
  EQUIPMENT_PURCHASE = 'EQUIPMENT_PURCHASE',
  MAINTENANCE = 'MAINTENANCE',
  REFRESHMENT = 'REFRESHMENT',
  COST_MANAGEMENT = 'COST_MANAGEMENT',
  OTHERS = 'OTHERS',
}
