export enum ApplicationStatus {
  PENDING_L0 = 'PENDING_L0',
  PENDING_L1 = 'PENDING_L1',
  PENDING_L2 = 'PENDING_L2',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum ApplicationType {
  LEAVE = 'LEAVE',
  EQUIPMENT = 'EQUIPMENT',
  EVENT_PROPOSAL = 'EVENT_PROPOSAL',
  NOC = 'NOC',
  GENERAL = 'GENERAL',
}
